FROM maven:3.5-jdk-8-alpine as builder
COPY ./my-app app
WORKDIR app/
RUN mvn clean package

FROM openjdk:8-jre-alpine3.9 as runtime
COPY --from=builder app/target/my-app-1.0.0.jar ./app/app.jar
RUN ls /app
ENTRYPOINT [ "java","-jar","/app/app.jar"]