name: Github actions + Docker pipeline
'on':
  push:
    branches:
      - master
  workflow_dispatch: null
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - checkout main branch from Github
        uses: actions/checkout@v3

      - name: Step 2 - Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Step 3 - Update POM Version
        run: mvn validate -DbumpPatch --file ./my-app/pom.xml

      - name: Step 4 - Build maven project
        run: mvn -B package --file ./my-app/pom.xml

      - name: Step 5 - check the target files
        run: |
          cd my-app/target
          ls -a

      - name: Step 6 - Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Step 7 - Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: '${{secrets.DOCKERHUB_USERNAME}}'
          password: '${{secrets.DOCKERHUB_TOKEN}}'

      - name: Step 8 - Build and push to docker hub
        env:
            version: $(mvn help:evaluate -Dexpression=project.version -q -DforceStdout --file ./my-app/pom.xml)

        run: |
          docker build -t ${{secrets.DOCKERHUB_USERNAME}}/java-hello:v${{ env.version }} --build-arg version=${{ env.version }} -f my-app/Dockerfile .
          docker push ${{secrets.DOCKERHUB_USERNAME}}/java-hello:v${{ env.version }}

      # - name: Step 9 - Build and push to docker hub
      #   id: docker_build
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: .
      #     file: ./my-app/Dockerfile
      #     push: true
      #     tags: ${{secrets.DOCKERHUB_USERNAME}}/maven-hello:v${{github.run_number}}