name: Github actions + Docker pipeline

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Step 1 - checkout main branch from Github
        uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Step 2 - Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      # Runs a set of commands using the runners shell
      - name: Step 3 - Build maven project
        run: mvn -B package --file ./my-app/pom.xml
          
      # Runs a set of commands using the runners shell
      - name: Step 4 - check the dir files
        run: ls -a

      # Runs a set of commands using the runners shell
      - name: Step 5 - check the target files
        run: |
          cd my-app/target
          ls -a

     - name: Step 6 - Setup Docker Buildx
       uses: docker/setup-buildx-action@v1
     
     - name: Step 7 - Login to DockerHub
       uses: docker/login-action@v1
       with:
         username: ${{ secrets.DOCKERHUB_USERNAME }}
         password: ${{ secrets.DOCKERHUB_TOKEN }}

     - name: Step 8 - Download artifact
       uses: actions/download-artifact@v2

     - name: Step 9 - Build and push to docker hub
       id: docker_build
       uses: docker/build-push-action@v2
       with:
         context: .
         push: true
         tags: ${{ secrets.DOCKERHUB_USERNAME }}/my-app/my-app-1.0.0.jar:v${{github.run_number}}